[package]
name = "little-lamb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chumsky = "0.11.1"
include_dir = "0.7.4"
thiserror = "2.0.17"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
paste = "1.0.15"
criterion = "0.7.0"

[[test]]
name = "examples_test"
path = "test/examples_test.rs"

[[bench]]
name = "substitution_bench"
harness = false

[[bench]]
name = "krivine_bench"
harness = false

[[bench]]
name = "kn_bench"
harness = false
